services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception

  wordpress:
    build:
      context: ./wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    build:
      context: ./mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
    driver: bridge
